### ISSUE TITLE
Canonical Tags and Robot Instructions

### ISSUE THREAD

**Issue by josephkazarian** [haassie/yoast_news#12]
Hello TYPO3 community,

Is it anyhow possible to use the Canonical Tag and the Robot Instructions fields for the EXT:news as it is available for pages?

Currently, the Canonical Tag is already there in the source code, but it's not editable from the backend, which makes it useless for the purpose of Canonical Tags.

![image](https://user-images.githubusercontent.com/9280492/104918768-87e71680-5995-11eb-818b-9a57497e40b4.png)

**Comment by ayacoo** [comment]
There is also already a canonical approach in the background. To avoid merge conflicts, one could first check the open PR (#21, #22) and release it if necessary.

**Comment by ste101** [comment]
@ayacoo 
Could you please provide your canonical approach here?
This would be great.
