### ISSUE TITLE
removing sitename?

### ISSUE THREAD

**Issue by toccamonium-fe** [haassie/yoast_news#15]
Hi, cool extension, thx!

Is there a way to remove the sitename in the title as I want to set everything manually?

cheers
Florian

**Comment by haassie** [comment]
Thanks a lot! This is a more general TYPO3 question though as this not only applies to the news records. It also depends on the TYPO3 version you use. I don't know if you're on TYPO3 slack, but if so: ask this question in the #cig-seo channel with some more detailed information and I'm sure I or somebody else can help you. I will close this issue for now.
