### ISSUE TITLE
v10 version?

### ISSUE THREAD

**Issue by prathers** [haassie/yoast_news#6]
Hi
Is there any work done in making this ext v10 compatible?

**Comment by josyjanga** [comment]
Hi, I am also interested in this question :-) Are there any news on that?
Thanks!

**Comment by Megafry** [comment]
The extension works fine without changes, I have updated the dependencies and made a pull requests.
if you want to try my version [yoast_news](https://github.com/Megafry/yoast_news).
Feel free to give feedback.

**Comment by haassie** [comment]
The master branch is v10 compatible. I will release a new version tomorrow.
